blank_issues_enabled: true
contact_links:
  - name: Ask on Gitter
    url: https://gitter.im/nektos/act
    about: You can ask for help here!
  - name: Ask on Gitter (via Matrix)
    url: https://matrix.to/#/#nektos_act:gitter.im?via=gitter.im&via=matrix.org
    about: If you prefer Matrix over Gitter
  - name: Want to contribute to act?
    url: https://github.com/nektos/act/blob/master/CONTRIBUTING.md
    about: Be sure to read contributing guidelines!
